trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - .editorconfig
    - .gitignore

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - .editorconfig
    - .gitignore

name: $(Build.BuildId)

variables:
- name: VMImage
  value: 'windows-2019'
- name: BuildConfiguration
  value: Release
- group: 'Code Signing'

stages:
- stage: build
  displayName: Build NuGet Packages
  jobs:
  - job: buildJob
    displayName: Build Container Extensions
    pool:
      vmImage: $(VMImage)
      demands:
      - MSBuild
    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: '3.0.100-preview5-011568'

    - task: NuGetToolInstaller@0
      displayName: Install Latest NuGet
      inputs:
        versionSpec: 4.9.4

    - task: NuGetCommand@2
      displayName: NuGet Restore
      inputs:
        noCache: true

    - task: MSBuild@1
      displayName: Build Projects
      inputs:
        configuration: $(BuildConfiguration)
        msbuildArguments: '/p:DebugType=portable'

    - powershell: |
       dotnet test .\tests\Prism.DryIoc.Extensions.Tests\Prism.DryIoc.Extensions.Tests.csproj --configuration $env:BuildConfiguration --logger trx --no-build --collect "Code Coverage"
       dotnet test .\tests\Prism.DryIoc.Forms.Extended.Tests\Prism.DryIoc.Forms.Extended.Tests.csproj --configuration $env:BuildConfiguration --logger trx --no-build --collect "Code Coverage"

      displayName: Run Unit Tests

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '**/*.trx'
        buildConfiguration: $(BuildConfiguration)

    - powershell: ./Sign-Packages.ps1
      workingDirectory: build
      displayName: Authenticode Sign Artifacts
      env:
        SignClientUser: $(SignClientUser)
        SignClientSecret: $(SignClientSecret)
        SignClientClientId: $(SignClientClientId)
        SignClientTenantId: $(SignClientTenantId)
        SignServiceResourceId: $(SignServiceResourceId)
      condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))

    - task: PublishPipelineArtifact@0
      displayName: Publish Artifacts
      inputs:
        artifactName: NuGet
        targetPath: $(Build.ArtifactStagingDirectory)

- stage: deploy
  displayName: Deploy NuGets
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))
  jobs:
  - deployment: MyGet
    displayName: MyGet.org
    environment: MyGet
    strategy:
      runOnce:
        deploy:
          steps:
          - task: NuGetCommand@2
            displayName: NuGet Push
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: 'Prism.Plugins - MyGet'

  - deployment: NuGet
    displayName: NuGet.org
    environment: NuGet
    condition: and(succeeded(), or(eq(variables['IS_PREVIEW'], true), eq(variables['IS_RELEASE'], true)))
    strategy:
      runOnce:
        deploy:
          steps:
          - powershell: $(System.DefaultWorkingDirectory)/build/Process-Release.ps1
            name: processName
            displayName: Process Artifacts for Release
            workingDirectory: $env:PIPELINE_WORKSPACE

          - task: GithubRelease@0 
            displayName: 'Create GitHub Release'
            inputs:
              githubConnection: 'GitHub - Dan Siegel'
              title: '$(ReleaseDisplayName)'
              tag: 'v$(VersionName)'
              isPreRelease: $(IS_PREVIEW)
              assets: '$(Pipeline.Workspace)/**/*.nupkg'
              addChangeLog: true
              isDraft: true

          - task: NuGetCommand@2
            displayName: NuGet Push
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;$(Pipeline.Workspace)/**/*.symbols.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: 'NuGet'
